# bases:
# - ../../base

# patches:
#  - replicas.yaml

# configMapGenerator:
# - name: mykustom-map
#   env: config.properties

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
