apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

labels:
- pairs:
    app: kustomwebapp

# Generate the ConfigMap required by your Deployment
configMapGenerator:
  - name: mykustom-map
    literals:
      - APP_ENV=production
      - DB_HOST=mydb.prod.svc.cluster.local
      - DB_PORT=5432
      - LOG_LEVEL=info

# bases:
# - ../../base

# patches:
#  - replicas.yaml

# configMapGenerator:
# - name: mykustom-map
#   env: config.properties
